#!/bin/bash
ref=$(awk '{{print $3}}' <&0)
version=$(echo $ref | awk -F/ '{{print $NF}}')
env
repo_name=$(echo $PWD | awk -F/ '{{print $NF}}' | awk -F. '{{print $1}}')
echo repo_name $repo_name
echo tag $tag
echo "REF:" $ref
D=$(mktemp -d)
git archive "$ref" | tar -x -C  $D
cd $D
docker build -t "${repo_name}:${version}" .
rm -rf $D
