#!/bin/bash
set -v
uid=$(stat -c '%u' /var/repos)
ent=$(getent passwd $uid)
if [ "$?" != "0" ] ; then
  USER_NAME="feh"
  useradd --uid $uid feh
else
    USER_NAME=$(getent passwd $uid | awk -F: '{{print $1}}')
fi

repo_owner=$USER_NAME
for i in "$REPOS" ; do
  if [ "" != "$i" ] ; then
      su ${repo_owner} -c "git init --bare /var/repos/$i.git"
      su ${repo_owner} -c "ln -s /var/repos/post-receive /var/repos/$i.git/hooks/post-receive"
  fi
done
sleep infinity

